dist: bionic
os: linux

install:
- source /opt/intel/inteloneapi/compiler/latest/env/vars.sh
addons:
    apt:
        sources:
        - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
          key_url: 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB'
        packages:
        - intel-oneapi-dpcpp-compiler

script:   
    - cd 9_sycl_of_hell; CXX=dpcpp make --keep-going


